name: Executar Pipeline de Dados

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v4

    - name: Preparar o Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Instalar as bibliotecas necessárias
      run: |
        pip install pandas sqlalchemy psycopg2-binary python-dotenv

    - name: Executar o pipeline de dados
      env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
      run: |
  cd projects/data-analysis/bank-customer-churn-analysis/python
  python pipeline.py
