name: Executar Pipeline de Dados

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: db_bank_customer_churn
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v4

    - name: Preparar o Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Instalar as bibliotecas necessárias
      run: |
        pip install pandas sqlalchemy psycopg2-binary python-dotenv

    - name: Executar o pipeline de dados
      env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: localhost
        DB_PORT: 5432
      run: |
        cd projects/data-analysis/bank-customer-churn-analysis/python
        python pipeline.py
